### ISSUE TITLE
Nav links overflow title on narrower screens before converting to mobile nav

### ISSUE THREAD

**Issue by novaugust** [TryGhost/London#1]
<img width="574" alt="screen shot 2019-01-03 at 11 19 32 am" src="https://user-images.githubusercontent.com/1207005/50654275-8a5eab00-0f49-11e9-8853-e1c97fe210e1.png">

**Comment by gnimmelf** [comment]
FYI, there is a similar issue on mobile layout (<850px); when the site title is long (enough), the nav-burger and title overlaps in the top right corner.

**Comment by daviddarnes** [comment]
Hey @novaugust and @gnimmelf. I've fixed this issue by allowing the navigation to wrap when there are a lot of navigation items. For mobile and small screens I've allowed the navigation to scroll. You can see demos below:
![Screenshot 2019-07-30 at 12 57 25](https://user-images.githubusercontent.com/1177460/62127694-9d144500-b2ca-11e9-9fba-317f2dcfb204.png)
![london-theme-mobile-nav](https://user-images.githubusercontent.com/1177460/62127714-a4d3e980-b2ca-11e9-97c9-ae07c46ef05e.gif)
