### ISSUE TITLE
no support  pagination?

### ISSUE THREAD

**Issue by StreetFlaneur** [TryGhost/London#15]
"posts_per_page": 6,   doesn‘t  work

**Comment by kevinansfield** [comment]
@StreetFlaneur this theme uses infinite scrolling, the only difference the `posts_per_page` setting will have is how many posts are fetched at a time in the background.

Can you explain what exactly "doesn't work" for you? What are you expecting to see, what's actually happening (or not)? Without any further details I'll close this issue as there is no information here.

**Comment by StreetFlaneur** [comment]
set  "posts_per_page": 6,   I  wish the home page display  6 posts and display the   pagination.
but the actually is the home page display all posts ,  when i click older post button of pagination, next page display the seventh post .
I hope for youe help.

**Comment by kevinansfield** [comment]
That's how infinite scroll works, there are no pagination controls visible it will automatically fetch the next page of posts whilst you scroll. If you want help modifying themes the best place to ask is on our forum https://forum.ghost.org/c/themes where you can get community support.

I'm going to close this issue as there is no bug here.
