### ISSUE TITLE
Swup not closing on mobile layout?

### ISSUE THREAD

**Issue by gnimmelf** [TryGhost/London#18]
Hi,

yesterday I had an issue with the swup(?)-menu not closing when clicking a link, but I was messing around with the theme, so I assumed it was me. Today I set up a fresh install of both Ghost and London, but the problem persists.

Can anyone confirm?

Cheers!

**Comment by daviddarnes** [comment]
Hey @gnimmelf! I don't suppose you could provide a link and test steps? Thanks
