### ISSUE TITLE
nav-burger Missing when making from source

### ISSUE THREAD

**Issue by joelbduncan** [TryGhost/London#196]
Hey,

When I built the unmodified source following the readme the menu on mobile does not appear unless clicked, this works fine on the pre-built version on ghost.org.

Invisible but still there
![image](https://user-images.githubusercontent.com/1405445/160825653-93578442-7af2-40b6-87a3-a3618411afdf.png)

Visible when dropped down
![image](https://user-images.githubusercontent.com/1405445/160825776-3b281305-6720-4f70-a95a-d8579f7ec82d.png)

Not sure where I'm going wrong or if this is a bug 😅

**Comment by minimaluminium** [comment]
Hey @joelbduncan,

Thanks for bringing this. That was definitely a bug, fixed in https://github.com/TryGhost/London/commit/6e89da87163ff1c518dec1c5301b54b6da5f4979.

Make sure pull the latest changes to your local repo, delete `node_modules` and install the dependencies again with `yarn` 🙂
