### ISSUE TITLE
Request for semver releases

### ISSUE THREAD

**Issue by JaneJeon** [TryGhost/London#207]
Hi, I love the theme and would like to say thanks for maintaining the theme.

However, as someone who wants to safely update my dependencies - including themes - I want to know whether something is "safe" to upgrade, whether something "new" has arrived, or whether something has changed.

The "mainline" Ghost themes (at least, Casper) do this by tagging the releases w/ a semver tag + some blurb about what changed in that release.

That would make upgrading this theme so much faster and safer. Could this theme also be released as various "cuts" of semver releases?

Thanks

**Comment by minimaluminium** [comment]
Hey, thanks for the feedback! We do releases only for Casper for simplicity at the moment. We haven't received enough requests for it as of now, but we'll definitely consider it if we do in the future.
