### ISSUE TITLE
tags are not shown in the post

### ISSUE THREAD

**Issue by calvintam236** [TryGhost/London#21]
user can't see what tags are tagged for the post

**Comment by rishabhgrg** [comment]
👋 Hey @calvintam236, thanks for reaching out. The theme is intentionally kept minimalistic, I'd suggest the best way to move forward will be forking it and adding custom changes(also #22 and #23) as desired. You can also take a look at [Casper](https://github.com/TryGhost/Casper) for inspiration on how to add some of the changes you mention.
