### ISSUE TITLE
Subscriber block is broken

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/London#3]
Hi,

John, awesome job over this theme! I tested it and I found this glitch:

![screen shot 2019-01-06 at 8 21 26 pm](https://user-images.githubusercontent.com/6694151/50744465-5efde980-11f1-11e9-9506-f607b9b82357.jpg)

For now, I will just disable the subscribers.

Thanks

### Details about my setup

* Ghost Version: 2.9.1
* CLI version: 1.9.4
* Node Version: 10.14.1
* Browser: Chrome 71
* OS X: 10.13.6
* Server: Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/jobs/428717032)
* Database: SQLite

**Comment by JohnONolan** [comment]
Subscribers is a beta feature not supported in this theme at present :) likely will be replaced with something new in the near future
