### ISSUE TITLE
Site title with long name obscures mobile menu

### ISSUE THREAD

**Issue by amwelles** [TryGhost/London#32]
When a site has a long title, the menu overlaps and obscures, making it difficult to see.

Example shown below.

![IMG_FE7D3EE5E461-1](https://user-images.githubusercontent.com/567160/67315585-df69ae80-f4d4-11e9-964d-25e4abf53fa2.jpeg)

**Comment by minimaluminium** [comment]
Hey @amwelles, sorry about the delay! You can make the site title a bit smaller on mobile screen with some CSS which you can enter in `Settings > Code injection > Site Header` field.

```html
<style>
@media (max-width: 850px) {
    .site-head-logo {
        font-size: 1.6rem;
        padding-top: 12px;
    }
}
</style>
```

And the final result would look like:

![Screen Shot 2020-09-03 at 5 23 05 PM](https://user-images.githubusercontent.com/1418797/92097455-ac898a00-ee0a-11ea-9dc5-f3b68cd61e54.png)
