### ISSUE TITLE
Divider line on Safari

### ISSUE THREAD

**Issue by ronaldlangeveld** [TryGhost/London#57]
Came across this on Safari with smaller screen sizes, generated by the `<hr>` tag. 
![image](https://user-images.githubusercontent.com/19263291/81961979-23b0cd80-9624-11ea-916f-ef615f5b4344.png)

Not sure if intended or not, because it doesn't appear on Chrome. 

Will for & try fix it over the weekend. :)

**Comment by minimaluminium** [comment]
Hey @ronaldlangeveld, sorry about the delay! The issue was fixed in 9e7c6e1.
