### ISSUE TITLE
How do I make all images of the home page blocky

### ISSUE THREAD

**Issue by Knighton910** [TryGhost/London#58]
Hi there, It's not really a problem with your code. 

Im trying to make the images on the homepage remain in a blocky image,
get rid of the long images, so it's really a structure issue. Any help would
be fantastic. Or should i move onto another them more like what i'm 
seeking.

**Comment by kevinansfield** [comment]
Hey @Knighton910 👋 Please use the [Themes category](https://forum.ghost.org/c/themes/8) on our forum for theming advice and support. We only use GitHub solely for tracking bugs and on-going feature work 🙂
