### ISSUE TITLE
Executable file

### ISSUE THREAD

**Issue by planetahuevo** [TryGhost/London#77]
Hi, 
This file is executable on the repo: 
https://github.com/TryGhost/London/blob/master/assets/built/swup.js

Which makes it fail on updates if you remove the executable permissions on the site installation.

**Comment by minimaluminium** [comment]
Hey @planetahuevo, it's fixed in https://github.com/TryGhost/London/commit/ec39525dd3de49aac083139a4297722627d6ab52. You can also verify this with `ghost doctor` command after installing the latest version of the theme.

**Comment by angelfplaza** [comment]
Thank you very much @minimaluminium I will give it a try! :)

**Comment by planetahuevo** [comment]
Thank you very much!! :)
